# Kubernetes Infrastructure Alerts
# Owner: Platform Team (@platform-oncall)
# Last Updated: 2024-11-10

groups:
  - name: kubernetes.pods
    interval: 30s
    rules:
      - alert: KubePodCrashLooping
        expr: |
          increase(kube_pod_container_status_restarts_total{namespace=~"production|staging"}[1h]) > 5
        for: 15m
        labels:
          severity: warning
          team: platform
          service: kubernetes
          tier: infrastructure
        annotations:
          summary: "Pod is crash looping"
          description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has restarted {{ $value }} times in the last hour."
          runbook_url: "https://runbooks.techcorp.io/kubernetes/pod-crash-loop"
          dashboard_url: "https://grafana.techcorp.io/d/kubernetes-pods"
          slack_channel: "#platform-alerts"

      - alert: KubePodNotReady
        expr: |
          sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown", namespace=~"production|staging"}) > 0
        for: 15m
        labels:
          severity: warning
          team: platform
          service: kubernetes
          tier: infrastructure
        annotations:
          summary: "Pod is not ready"
          description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in {{ $labels.phase }} state for more than 15 minutes."
          runbook_url: "https://runbooks.techcorp.io/kubernetes/pod-not-ready"
          dashboard_url: "https://grafana.techcorp.io/d/kubernetes-pods"
          slack_channel: "#platform-alerts"

  - name: kubernetes.nodes
    interval: 30s
    rules:
      - alert: KubeNodeNotReady
        expr: kube_node_status_condition{condition="Ready", status="true"} == 0
        for: 5m
        labels:
          severity: critical
          team: platform
          service: kubernetes
          tier: infrastructure
          pagerduty: enabled
        annotations:
          summary: "Kubernetes node not ready"
          description: "Node {{ $labels.node }} is not ready. Workloads may be disrupted."
          runbook_url: "https://runbooks.techcorp.io/kubernetes/node-not-ready"
          dashboard_url: "https://grafana.techcorp.io/d/kubernetes-nodes"
          slack_channel: "#platform-alerts"

      - alert: KubeNodeMemoryPressure
        expr: kube_node_status_condition{condition="MemoryPressure", status="true"} == 1
        for: 5m
        labels:
          severity: warning
          team: platform
          service: kubernetes
          tier: infrastructure
        annotations:
          summary: "Node under memory pressure"
          description: "Node {{ $labels.node }} is under memory pressure. Pods may be evicted."
          runbook_url: "https://runbooks.techcorp.io/kubernetes/node-memory-pressure"
          dashboard_url: "https://grafana.techcorp.io/d/kubernetes-nodes"
          slack_channel: "#platform-alerts"

      - alert: KubeNodeDiskPressure
        expr: kube_node_status_condition{condition="DiskPressure", status="true"} == 1
        for: 5m
        labels:
          severity: warning
          team: platform
          service: kubernetes
          tier: infrastructure
        annotations:
          summary: "Node under disk pressure"
          description: "Node {{ $labels.node }} is under disk pressure. Pods may be evicted."
          runbook_url: "https://runbooks.techcorp.io/kubernetes/node-disk-pressure"
          dashboard_url: "https://grafana.techcorp.io/d/kubernetes-nodes"
          slack_channel: "#platform-alerts"


